analyze_brandbook:
  description: >
    Gebruik de tool om het brandbook PDF-bestand op pad '{brandbook_path}' te analyseren.
    Haal hieruit enkel het volgende in JSON-formaat:
    - Primaire en secundaire kleuren (met HEX-codes)
    - Gebruikte fonts en stijlen
    - Richtlijnen voor logogebruik
    - Een korte beschrijving van de visuele stijl (maximaal 3 zinnen)
  expected_output: >
    JSON met de brandinginformatie zoals hierboven beschreven
  agent: brandbook_analyst
  input_vars: ["brandbook_path"]

analyze_tone:
  description: >
    Gebruik de tool 'ToneOfVoiceExtractor' om de website op '{website_url}' te analyseren.
    Geef een JSON terug met 3 kernwoorden en voor elk woord een korte uitleg in 1 zin.
  expected_output: >
    JSON met drie tone-woorden en hun verklaringen
  agent: tone_analyst
  input_vars: ["website_url"]

build_prompt:
  description: >
    Maak een designprompt op basis van het doel ('{goal}'), de doelgroep ('{audience}'),
    de eerder geanalyseerde brandinginformatie en tone-of-voice. Combineer dit alles
    tot een gestructureerde instructie voor een designer in JSON-vorm.
  expected_output: >
    JSON met design_instruction, inclusief kleuren, fonts, toon, visuele stijl en ontwerpinstructies
  agent: prompt_composer
  input_vars: ["brandbook_json", "tone_json", "goal", "audience"]
