analyze_tone:
  description: >
    Gebruik de tool 'ToneOfVoiceExtractor' om de website op '{website_url}' te analyseren.
    Geef een JSON terug met 3 kernwoorden en voor elk woord een korte uitleg in 1 zin.
  expected_output: >
    JSON met drie tone-woorden en hun verklaringen
  agent: tone_of_voice_analyzer
  input_vars: ["website_url"]

analyze_brandbook:
  description: >
    Gebruik de tool om het brandbook PDF-bestand op pad '{brandbook_path}' te analyseren.
    Haal hieruit enkel het volgende in JSON-formaat:
    - Primaire en secundaire kleuren (met HEX-codes)
    - Gebruikte fonts en stijlen
    - Richtlijnen voor logogebruik
    - Een korte beschrijving van de visuele stijl (maximaal 3 zinnen)
  expected_output: >
    JSON met de brandinginformatie zoals hierboven beschreven
  agent: brandbook_analyzer
  input_vars: ["brandbook_path"]

# analyze_style:
#   description: >
#     Analyseer de stijl van eerdere ontwerpen voor klant '{client_name}'.
#   expected_output: >
#     JSON met beschrijving van visuele stijl, indeling, kleuren en fonts.
#   agent: style_analyzer
#   input_vars: ["client_name"]

build_prompt:
  description: >
    Maak een designprompt op basis van het doel ('{goal}'), de doelgroep ('{audience}'),
    de eerder geanalyseerde brandinginformatie en tone-of-voice. Combineer dit alles
    tot een gestructureerde instructie voor een designer in JSON-vorm.
  expected_output: >
    JSON met design_instruction, inclusief kleuren, fonts, toon, visuele stijl en ontwerpinstructies
  agent: prompt_builder
  input_vars: ["brandbook_json", "tone_json", "goal", "audience"]

generate_design:
  description: >
    Bouw het ontwerp op basis van briefing en stijl.
  expected_output: >
    JSON met finale instructie en designdetails.
  agent: design_builder
  input_vars: ["design_prompt_json"]